#!/bin/bash

#python val.py --data qr_code.yaml --weights ../Complete_SUIT_Dataset/yolo_s/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo_s --name yolo_out --save-txt --save-hybrid --task test --conf-thres 0.5;
#python val.py --data qr_code.yaml --weights ../Complete_SUIT_Dataset/yolo_n/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo_n --name yolo_out --save-txt --save-hybrid --task test --conf-thres 0.5;
#python val.py --data qr_code.yaml --weights ../Complete_SUIT_Dataset/yolo_m/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo_m --name yolo_out --save-txt --save-hybrid --task test --conf-thres 0.5;
#python val.py --data qr_code.yaml --weights ../Complete_SUIT_Dataset/yolo_l/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo_l --name yolo_out --save-txt --save-hybrid --task test --conf-thres 0.5;
#
#python val.py --data qr_code_fpt.yaml --weights ../Complete_SUIT_Dataset/yolo_s/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo_s --name no_label --save-txt --save-hybrid --task test --conf-thres 0.5;
#python val.py --data qr_code_fpt.yaml --weights ../Complete_SUIT_Dataset/yolo_n/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo_n --name no_label --save-txt --save-hybrid --task test --conf-thres 0.5;
#python val.py --data qr_code_fpt.yaml --weights ../Complete_SUIT_Dataset/yolo_m/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo_m --name no_label --save-txt --save-hybrid --task test --conf-thres 0.5;
#python val.py --data qr_code_fpt.yaml --weights ../Complete_SUIT_Dataset/yolo_l/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo_l --name no_label --save-txt --save-hybrid --task test --conf-thres 0.5;

# color correction
#python val.py --data qr_code-HUA.yaml --weights ../Complete_SUIT_Dataset/yolo/exp4/HUA/color_correction_transform/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo/exp4/HUA/color_correction_transform/exp --name test_output --save-txt --save-hybrid --task test --conf-thres 0.5;
#python val.py --data qr_code-LL.yaml --weights ../Complete_SUIT_Dataset/yolo/exp4/HUA/color_correction_transform/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo/exp4/LL/color_correction_transform/exp --name test_output --save-txt --save-hybrid --task test --conf-thres 0.5;
#python val.py --data qr_code-MOO.yaml --weights ../Complete_SUIT_Dataset/yolo/exp4/HUA/color_correction_transform/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo/exp4/MOO/color_correction_transform/exp --name test_output --save-txt --save-hybrid --task test --conf-thres 0.5;
#python val.py --data qr_code-PAL.yaml --weights ../Complete_SUIT_Dataset/yolo/exp4/HUA/color_correction_transform/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo/exp4/PAL/color_correction_transform/exp --name test_output --save-txt --save-hybrid --task test --conf-thres 0.5;
#python val.py --data qr_code-RAI.yaml --weights ../Complete_SUIT_Dataset/yolo/exp4/HUA/color_correction_transform/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo/exp4/RAI/color_correction_transform/exp --name test_output --save-txt --save-hybrid --task test --conf-thres 0.5;
#python val.py --data qr_code-TAH.yaml --weights ../Complete_SUIT_Dataset/yolo/exp4/HUA/color_correction_transform/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo/exp4/TAH/color_correction_transform/exp --name test_output --save-txt --save-hybrid --task test --conf-thres 0.5;
#python val.py --data qr_code-TTR.yaml --weights ../Complete_SUIT_Dataset/yolo/exp4/HUA/color_correction_transform/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo/exp4/TTR/color_correction_transform/exp --name test_output --save-txt --save-hybrid --task test --conf-thres 0.5;

# default_transform
python val.py --data qr_code-HUA.yaml --weights ../Complete_SUIT_Dataset/yolo/exp4/HUA/default_transform/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo/exp4/HUA/default_transform/exp_with_aug --name test_output --save-txt --save-hybrid --task test --augment --verbose;
python val.py --data qr_code-LL.yaml --weights ../Complete_SUIT_Dataset/yolo/exp4/HUA/default_transform/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo/exp4/LL/default_transform/exp_with_aug --name test_output --save-txt --save-hybrid --task test --augment --verbose;
python val.py --data qr_code-MOO.yaml --weights ../Complete_SUIT_Dataset/yolo/exp4/HUA/default_transform/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo/exp4/MOO/default_transform/exp_with_aug --name test_output --save-txt --save-hybrid --task test --augment --verbose;
python val.py --data qr_code-PAL.yaml --weights ../Complete_SUIT_Dataset/yolo/exp4/HUA/default_transform/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo/exp4/PAL/default_transform/exp_with_aug --name test_output --save-txt --save-hybrid --task test --augment --verbose;
python val.py --data qr_code-RAI.yaml --weights ../Complete_SUIT_Dataset/yolo/exp4/HUA/default_transform/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo/exp4/RAI/default_transform/exp_with_aug --name test_output --save-txt --save-hybrid --task test --augment --verbose;
python val.py --data qr_code-TAH.yaml --weights ../Complete_SUIT_Dataset/yolo/exp4/HUA/default_transform/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo/exp4/TAH/default_transform/exp_with_aug --name test_output --save-txt --save-hybrid --task test --augment --verbose;
python val.py --data qr_code-TTR.yaml --weights ../Complete_SUIT_Dataset/yolo/exp4/HUA/default_transform/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo/exp4/TTR/default_transform/exp_with_aug --name test_output --save-txt --save-hybrid --task test --augment --verbose;

# intensive_transform
#python -W ignore val.py --data qr_code-HUA.yaml --weights ../Complete_SUIT_Dataset/yolo/exp4/HUA/intensive_transform/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo/exp4/HUA/intensive_transform/exp/test_with_aug --name test_output --save-txt --save-hybrid --task test --conf-thres 0.5 --augment --verbose;
#python -W ignore val.py --data qr_code-LL.yaml --weights ../Complete_SUIT_Dataset/yolo/exp4/HUA/intensive_transform/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo/exp4/LL/intensive_transform/exp/test_with_aug --name test_output --save-txt --save-hybrid --task test --conf-thres 0.5 --augment --verbose;
#python -W ignore val.py --data qr_code-MOO.yaml --weights ../Complete_SUIT_Dataset/yolo/exp4/HUA/intensive_transform/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo/exp4/MOO/intensive_transform/exp/test_with_aug --name test_output --save-txt --save-hybrid --task test --conf-thres 0.5 --augment --verbose;
#python -W ignore val.py --data qr_code-PAL.yaml --weights ../Complete_SUIT_Dataset/yolo/exp4/HUA/intensive_transform/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo/exp4/PAL/intensive_transform/exp/test_with_aug --name test_output --save-txt --save-hybrid --task test --conf-thres 0.5 --augment --verbose;
#python -W ignore val.py --data qr_code-RAI.yaml --weights ../Complete_SUIT_Dataset/yolo/exp4/HUA/intensive_transform/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo/exp4/RAI/intensive_transform/exp/test_with_aug --name test_output --save-txt --save-hybrid --task test --conf-thres 0.5 --augment --verbose;
#python -W ignore val.py --data qr_code-TAH.yaml --weights ../Complete_SUIT_Dataset/yolo/exp4/HUA/intensive_transform/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo/exp4/TAH/intensive_transform/exp/test_with_aug --name test_output --save-txt --save-hybrid --task test --conf-thres 0.5 --augment --verbose;
#python -W ignore val.py --data qr_code-TTR.yaml --weights ../Complete_SUIT_Dataset/yolo/exp4/HUA/intensive_transform/exp/weights/best.pt --img 640 --project ../Complete_SUIT_Dataset/yolo/exp4/TTR/intensive_transform/exp/test_with_aug --name test_output --save-txt --save-hybrid --task test --conf-thres 0.5 --augment --verbose;
